## Numpy
##### NumPy (Numerical Python) is a fundamental Python library for numerical computing. It offers support for large, multi-dimensional arrays and matrices, along with a wide range of mathematical functions to manipulate these arrays. NumPy serves as the backbone for many other data science and machine learning libraries, including Pandas, SciPy, and TensorFlow.

# Why Numpy
##### NumPy is popular because it can handle large datasets efficiently. Unlike Python lists, NumPy arrays (ndarrays) use less memory and work faster for math-related tasks. This makes it especially useful for big data projects in areas like data science, machine learning, and scientific research.

## What This Library Does
#### N-dimensional Arrays (ndarray)
#### Explanation:
##### The main data structure in NumPy is the ndarray, which stands for "N-dimensional array." Unlike a standard matrix, an ndarray can have any number of dimensions, making it highly versatile for different types of data manipulation.

#### Why Use NumPy Arrays Instead of Python Lists?
##### Homogeneous Data: NumPy arrays are designed to store data of the same type, which makes them more memory-efficient and faster to process compared to Python lists that can hold mixed data types.

##### Vectorized Operations: Operations on NumPy arrays are automatically applied element-wise, known as vectorization. This allows you to avoid writing explicit loops, making the code simpler and more efficient.

##### Broadcasting: NumPy allows you to perform operations on arrays with different shapes and sizes without needing to resize or copy them manually. This feature, called broadcasting, simplifies many types of calculations.


## When should you use NumPy?

##### NumPy is ideal when working with numerical data and performing mathematical operations. It is especially helpful for:

#### Array Handling: NumPy offers flexible tools for creating, reshaping, and manipulating arrays.

#### Mathematical Operations: It provides a variety of mathematical functions, including statistics, algebra, and trigonometry.

#### Efficiency: Optimized for performance, NumPy is well-suited for handling large datasets efficiently.

In [ ]:
# Creating a 1D array

In [23]:
import numpy as np

array_1d = np.array([1, 2, 3, 4, 5])
print(array_1d)
type(array_1d)

[1 2 3 4 5]


numpy.ndarray

# 3D Array

In [25]:
# Creating a 2D Numpy array (matrix)
matrix = np.array([[1, 2, 3], [4, 5, 6]])
print(matrix)

[[1 2 3]
 [4 5 6]]


# 2. Mathematical Operations

#### Example 1: Element-wise operations
##### 1. Basic Arithmetic Operations
##### You can easily perform element-wise operations on NumPy arrays.

In [27]:
# Creating an array and performing element-wise operations
array = np.array([1, 2, 3, 4])
array = array + 10
print(array)

[11 12 13 14]


In [29]:
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Element-wise addition, subtraction, multiplication, and division
add = a + b
subtract = a - b
multiply = a * b
divide = a / b

print("Addition:", add)
print("Subtraction:", subtract)
print("Multiplication:", multiply)
print("Division:", divide)


Addition: [5 7 9]
Subtraction: [-3 -3 -3]
Multiplication: [ 4 10 18]
Division: [0.25 0.4  0.5 ]


<!-- list is different from array -->

# Example 2: Matrix multiplication
### Linear Algebra
### You can perform matrix operations such as matrix multiplication, transpose, and finding the inverse.

A = [a11   a12]        
    [a21   a22]
    
B=  [b11    b12]
    [b21    b22]
    
    
A.B = [a11.b11+a12.b21    a11.b12+a12.b22]
    [a21.b12+a22.b21      a21.b12+a22.b22]

note: A.B != B.A

In [28]:
# Example 2: Matrix multiplication
matrix_a = np.array([[1,2],[3,4]])
matrix_b = np.array([[5,6],[7,8]])
prod = np.dot(matrix_a, matrix_b)
print(prod)
prod1 = np.dot(matrix_b, matrix_a)
print(prod1)


[[19 22]
 [43 50]]
[[23 34]
 [31 46]]


## 3. Statistical Functions
### NumPy includes built-in functions to compute common statistics, such as mean, median, and standard deviation.

In [30]:
# Statistical operations
array = np.array([1, 2, 3, 4, 5])

mean = np.mean(array)         # Mean
median = np.median(array)     # Median
std_dev = np.std(array)       # Standard deviation

print("Mean:", mean)
print("Median:", median)
print("Standard Deviation:", std_dev)


Mean: 3.0
Median: 3.0
Standard Deviation: 1.4142135623730951


# 4. Advanced Array Operations
##### Array Slicing and Indexing : Slicing and indexing in NumPy let you retrieve or modify specific elements or portions of an array. While similar to slicing Python lists, NumPy provides more advanced and flexible functionality.

### array[start:stop:step]


In [31]:
arr = np.array([0, 1, 2, 3, 4, 5])

# Basic slicing
sliced_arr = arr[1:5]   # Extract elements from index 1 to 4
print(sliced_arr)


[1 2 3 4]


### 2. Slicing a 2D Array

In [34]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3], 
                   [4, 5, 6], 
                   [7, 8, 9]])
print(arr_2d,'\n')

# Extract a subset of the array
sliced_2d = arr_2d[0:2, 1:3]  # Extract rows 0-1 and columns 1-2
print(sliced_2d)


[[1 2 3]
 [4 5 6]
 [7 8 9]] 

[[2 3]
 [5 6]]


In [37]:
matrix = np.array([[1, 2, 3], [4, 5, 6], [7, 8, 9]])
slice_2 = matrix[:2, 1:3]  # Access a submatrix
print(slice_2)

[[2 3]
 [5 6]]


### 3. Using Step in Slicing

In [36]:
# Using step size
arr = np.array([0, 1, 2, 3, 4, 5, 6, 7])
print(arr,'\n')

# Slice with a step of 2
sliced_step = arr[::2]
print(sliced_step)


[0 1 2 3 4 5 6 7] 

[0 2 4 6]


### Filtering with Boolean Indexing in NumPy: 
##### Boolean indexing allows you to select elements from an array based on conditions. You create a boolean array (an array of True and False values) that indicates which elements meet the specified condition.

In [38]:
array = np.array([10, 20, 30, 40, 50])
filtered_array = array[array > 25]  # Filter elements greater than 25
print(filtered_array)


[30 40 50]


In [39]:
# Filter elements greater than 15 and less than 35
filtered_combined = arr[(arr > 15) & (arr < 35)]
print(filtered_combined)


[]


# Mathematical Functions

### sum

In [40]:
# Creating an array
arr = np.array([1, 2, 3, 4, 5])

# Sum of all elements
total_sum = np.sum(arr)
print("Sum:", total_sum)


Sum: 15


## 2. Mean
### Calculates the average of the elements in the array.

In [41]:
# Mean of the array
mean_value = np.mean(arr)
print("Mean:", mean_value)

Mean: 3.0


## 3. Minimum and Maximum
#### Finds the minimum and maximum values in the array.

In [43]:
# Minimum and maximum values
min_value = np.min(arr)
max_value = np.max(arr)

print("Minimum:", min_value)
print("Maximum:", max_value)


Minimum: 1
Maximum: 5


### 4. Aggregation Along an Axis
##### You can also compute aggregations along specific axes in multi-dimensional arrays.

In [44]:
# Creating a 2D array
arr_2d = np.array([[1, 2, 3],
                   [4, 5, 6],
                   [7, 8, 9]])

# Sum along rows (axis=0) and columns (axis=1)
sum_rows = np.sum(arr_2d, axis=0)  # Sum of each column
sum_columns = np.sum(arr_2d, axis=1)  # Sum of each row

print("Sum along rows:", sum_rows)
print("Sum along columns:", sum_columns)


Sum along rows: [12 15 18]
Sum along columns: [ 6 15 24]


## Dot Product of Vectors in NumPy
#### You can calculate the dot product using the numpy.dot() function or the @ operator in NumPy.

#### Explanation :In the example above, the dot product is calculated as follows:

### 1×4+2×5+3×6=4+10+18=32

In [45]:
import numpy as np

# Creating two 1D arrays (vectors)
a = np.array([1, 2, 3])
b = np.array([4, 5, 6])

# Calculating the dot product
dot_product = np.dot(a, b)
print("Dot Product using numpy.dot():", dot_product)


Dot Product using numpy.dot(): 32


In [47]:
matrix_a = np.array([[1, 2], [3, 4]])
matrix_b = np.array([[5, 6], [7, 8]])
product = np.dot(matrix_a, matrix_b)
print(product)

[[19 22]
 [43 50]]


In [46]:
# Calculating the dot product using the @ operator
dot_product_operator = a @ b
print("Dot Product using @ operator:", dot_product_operator)


Dot Product using @ operator: 32


### Random Number Generation in NumPy
#### 1. Generating Random Floats ---numpy.random.rand().

In [48]:
import numpy as np

# Generate an array of random floats (between 0 and 1)
random_floats = np.random.rand(5)  # Generates 5 random floats
print("Random Floats:", random_floats)


Random Floats: [0.00157513 0.43793902 0.6778417  0.55802403 0.31613429]


### 2. Generating Random Integers
#### numpy.random.randint() --to generate random integers within a specified range.

In [49]:
# Generate random integers between 10 and 50 (exclusive)
random_integers = np.random.randint(10, 50, size=5)  # Generates 5 random integers
print("Random Integers:", random_integers)


Random Integers: [49 39 17 37 38]


### 3. Generating Random Samples from a Normal Distribution
#### You can generate random numbers following a normal (Gaussian) distribution using numpy.
### numpy.random.normal().

In [50]:
# Generate random samples from a normal distribution
mean = 0      # Mean of the distribution
std_dev = 1  # Standard deviation
normal_samples = np.random.normal(mean, std_dev, size=5)  # Generates 5 samples
print("Normal Distribution Samples:", normal_samples)


Normal Distribution Samples: [ 0.28833466  0.41546057  1.03864625 -0.89383402  1.01791425]


In [53]:
normal_array = np.random.randn(3, 3)  # 3x3 matrix of normally distributed numbers
print(normal_array)


[[ 1.02578137 -1.3999101  -0.06864188]
 [ 0.03065506 -0.79112057  0.18495561]
 [ 1.97084576  1.73261228 -0.35264174]]


### 4. Generating Random Samples from a Uniform Distribution
#### You can generate random samples uniformly distributed between specified minimum and maximum
### numpy.random.uniform().

In [51]:
# Generate random samples from a uniform distribution
uniform_samples = np.random.uniform(low=0.0, high=10.0, size=5)  # Generates 5 samples
print("Uniform Distribution Samples:", uniform_samples)


Uniform Distribution Samples: [8.49480444 9.08725833 1.54284892 9.3703081  9.27532861]


In [52]:
random_array = np.random.rand(3, 3)  # 3x3 matrix of random numbers
print(random_array)


[[3.96685107e-01 1.84469145e-01 4.86059686e-01]
 [8.27709625e-01 4.70411670e-01 8.10246440e-01]
 [4.31003225e-04 4.81777774e-01 6.43424908e-01]]


### 5. Setting a Random Seed
#### To make the random numbers reproducible, you can set a seed using numpy.random.seed(). This ensures that the same random numbers are generated each time the code is run.
### numpy.random.seed()

In [54]:
# Set a random seed
np.random.seed(42)

# Generate random floats
random_floats_seeded = np.random.rand(5)
print("Random Floats with Seed:", random_floats_seeded)


Random Floats with Seed: [0.37454012 0.95071431 0.73199394 0.59865848 0.15601864]
